/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<'index', '/', Record<never, never>, Record<never, never>>,
    'index.dashboard': RouteRecordInfo<'index.dashboard', '', Record<never, never>, Record<never, never>>,
    'index.datatable.index': RouteRecordInfo<'index.datatable.index', '/datatable', Record<never, never>, Record<never, never>>,
    'index.datatable.create': RouteRecordInfo<'index.datatable.create', '/datatable/create', Record<never, never>, Record<never, never>>,
    '[...404]': RouteRecordInfo<'[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    'auth': RouteRecordInfo<'auth', '/auth', Record<never, never>, Record<never, never>>,
    'auth.forgot-password': RouteRecordInfo<'auth.forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'auth.login': RouteRecordInfo<'auth.login', '/login', Record<never, never>, Record<never, never>>,
    'auth.reset-password.[token]': RouteRecordInfo<'auth.reset-password.[token]', '/reset-password/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    'auth.logout': RouteRecordInfo<'auth.logout', '/auth/logout', Record<never, never>, Record<never, never>>,
    'auth.recovery': RouteRecordInfo<'auth.recovery', '/auth/recovery', Record<never, never>, Record<never, never>>,
    'auth.redirect': RouteRecordInfo<'auth.redirect', '/auth/redirect', Record<never, never>, Record<never, never>>,
    'auth.verify': RouteRecordInfo<'auth.verify', '/auth/verify', Record<never, never>, Record<never, never>>,
  }
}
